imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @SimpleAdminBundle/Resources/config/admin.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
      - SimpleAdminBundle
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
          jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_css:
          jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc
        auto_mapping: true

sonata_media:
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    class:
        media:              SimpleAdmin\Bundle\SimpleAdminBundle\Entity\Media
        gallery:            SimpleAdmin\Bundle\SimpleAdminBundle\Entity\Gallery
        gallery_has_media:  SimpleAdmin\Bundle\SimpleAdminBundle\Entity\GalleryHasMedia
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 60,  height: 60,  quality: 70}
                medium: { width: 95,  height: 95,  quality: 70}
                big:   { width: 150, height: 150, quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false

    providers:
            image:
                resizer: sonata.media.resizer.square

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

# app/config/config.yml
sonata_admin:
    title:      Sonata Project
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
    param_fetcher_listener: true
    body_listener:
      decoders:
        json: fos_rest.decoder.json
        xml: fos_rest.decoder.xml
    format_listener:
      rules:
        - { path: '^/api/', priorities: [ 'json','xml'], fallback_format 'json', prefer_extension: false }
        - { path: '^/', priorities: ['html','*/*'], fallback_format: 'html', prefer_extension: false }

    view:
      view_response_listener: force
      default_engine:         twig

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: SimpleAdmin\Bundle\SimpleAdminBundle\Entity\User

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_js_routing:
    routes_to_expose: [ api_get_managed_entities, api_get_listing_window, simpleadmin_simpleadmin_simpleadmin_listingwindowtemplate]

jms_di_extra:
    locations:
        all_bundles: true
        bundles: [SimpleAdminBundle]
        directories: ["%kernel.root_dir%/../src","%kernel.root_dir%/../src/SimpleAdmin/Bundle/SimpleAdminBundle/Listener"]


simple_admin:
    manage:
      entities:
        - {name: 'Person', entity: 'SimpleAdminBundle:Person', columns: [{field: id, alias: id},{field: name, alias: nombre}], filters:[{field: name,type: text, label: "Name" },{field: lastName, type:text,label: "Last name"},{field: country, type:select,label: "Country", entity: "SimpleAdminBundle:Country", entity_order: "name",entity_description_field: "name", entity_pk_field: "id" }]}
        - {name: 'User', entity: 'SimpleAdminBundle:User'}
        - {name: 'Nested Test', children: [{name: 'User', entity: 'SimpleAdminBundle:User'}]}