_default:
    pattern:  /
    defaults: { _controller: SimpleAdminBundle:Default:default }

SimpleAdminBundle:
    resource: "@SimpleAdminBundle/Controller"
    prefix:   /simpleadmin
    type: annotation

