parameters:
#    simple_admin.example.class: SimpleAdmin\Bundle\SimpleAdminBundle\Example

services:
#    simple_admin.example:
#        class: %simple_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     fpdf:
        class: SimpleAdmin\Bundle\SimpleAdminBundle\Service\FPDF
        arguments: ['L','pt']
